export const shapes = [
    { top: "10%", left: "15%", bg: "teal, lightblue", animationDuration: "6s" },
    {
        top: "30%",
        left: "80%",
        bg: "blue, navy",
        width: "106px",
        height: "106px",
        animationDuration: "8s",
        opacity: 0.5,
    },
    {
        top: "70%",
        left: "30%",
        bg: "teal, darkblue",
        width: "66px",
        height: "66px",
        borderRadius: "10px",
        animationDuration: "5s",
        opacity: 0.6,
    },
    {
        top: "50%",
        left: "60%",
        bg: "blue, teal",
        width: "56px",
        height: "56px",
        animationDuration: "6.5s",
        opacity: 0.4,
    },
    {
        top: "85%",
        left: "50%",
        bg: "lightblue, teal",
        width: "76px",
        height: "76px",
        animationDuration: "7.5s",
        opacity: 0.3,
    },
    {
        top: "25%",
        left: "90%",
        bg: "lightblue, teal",
        width: "96px",
        height: "96px",
        borderRadius: "15%",
        animationDuration: "9s",
        opacity: 0.4,
    },
    {
        top: "15%",
        left: "50%",
        bg: "green, lime",
        width: "96px",
        height: "96px",
        borderRadius: "15%",
        animationDuration: "9s",
        opacity: 0.4,
    },
    {
        top: "75%",
        left: "10%",
        bg: "green, lime",
        width: "96px",
        height: "96px",
        borderRadius: "50%",
        animationDuration: "9s",
        opacity: 0.4,
    },
    {
        top: "80%",
        left: "90%",
        bg: "green, lime",
        width: "96px",
        height: "96px",
        borderRadius: "50%",
        animationDuration: "9s",
        opacity: 0.4,
    },
];
